const usernames = [
  "Aaran",
  "Aaren",
  "Aarez",
  "Aarman",
  "Aaron",
  "Aaron-James",
  "Aarron",
  "Aaryan",
  "Aaryn",
  "Aayan",
  "Aazaan",
  "Abaan",
  "Abbas",
  "Abdallah",
  "Abdalroof",
  "Abdihakim",
  "Abdirahman",
  "Abdisalam",
  "Abdul",
  "Abdul-Aziz",
  "Abdulbasir",
  "Abdulkadir",
  "Abdulkarem",
  "Smith",
  "Jones",
  "Coollastname",
  "enter_name_here",
  "Ze",
  "Zechariah",
  "Zeek",
  "Zeeshan",
  "Zeid",
  "Zein",
  "Zen",
  "Zendel",
  "Zenith",
  "Zennon",
  "Zeph",
  "Zerah",
  "Zhen",
  "Zhi",
  "Zhong",
  "Zhuo",
  "Zi",
  "Zidane",
  "Zijie",
  "Zinedine",
  "Zion",
  "Zishan",
  "Ziya",
  "Ziyaan",
  "Zohaib",
  "Zohair",
  "Zoubaeir",
  "Zubair",
  "Zubayr",
  "Zuriel",
  "Xander",
  "Jared",
  "Courtney",
  "Gillian",
  "Clark",
  "Jared",
  "Grace",
  "Kelsey",
  "Tamar",
  "Alex",
  "Mark",
  "Tamar",
  "Farish",
  "Sarah",
  "Nathaniel",
  "Parker",
];

const thoughts = [
  "Just had the most amazing adventure! #TravelGoals 🌍✈️ Can't wait to share all the stunning photos with you!",
  "Exciting news! My new book is finally out and available on all major platforms. Check it out and let me know what you think! 📚🎉",
  "Feeling grateful for all the love and support I've received. You guys are the best! ❤️ #Grateful",
  "Spent the day exploring hidden gems in the city. Found this cozy café with the most delicious pastries. Highly recommend! ☕️🥐 #Foodie",
  "Just finished an intense workout session. Feeling the burn, but it's totally worth it! 💪💦 #FitnessGoals",
  "Had an incredible time at the concert last night. The energy was off the charts! 🎶🔥 #MusicLover",
  "Enjoying a lazy Sunday morning with a cup of coffee and a good book. Blissful! ☕️📖 #SundayVibes",
  "Counting down the days until my next vacation. Need some time to relax and recharge. 🏖️✨ #VacationMode",
  "Spent the afternoon volunteering at a local shelter. The joy on the kids' faces was priceless! 🤗❤️ #GivingBack",
  "Trying out a new recipe tonight. Fingers crossed it turns out as delicious as it looks! 🍳🥗 #CookingAdventures",
  "Just watched the most inspiring documentary. It shed light on important global issues. #Awareness",
  "Exploring new horizons and embracing new experiences. Life is too short to stay in your comfort zone! #AdventureTime",
  "Celebrating a milestone today! It's been an incredible journey, and I'm grateful for everyone who has been part of it. 🎉 #AchievementUnlocked",
  "Spent the day at the beach, basking in the sun and enjoying the sound of crashing waves. Pure bliss! 🏖️☀️ #BeachVibes",
  "Attended an enlightening workshop on personal growth and self-improvement. Feeling motivated and ready to take on new challenges! 💪 #PersonalDevelopment",
  "Nothing beats a cozy movie night at home with popcorn and a good film. Any movie recommendations? 🍿🎥 #MovieNight",
  "Had an amazing time exploring the vibrant street art scene in the city. So much talent and creativity! 🎨✨ #ArtisticExpression",
  "Just finished reading an inspiring book that made me see the world from a different perspective. Highly recommend it! 📚 #Bookworm",
  "Taking a break from the digital world and reconnecting with nature. It's refreshing and rejuvenating! 🌳🍃 #DigitalDetox",
  "Enjoying a cup of hot chocolate on a rainy day. The perfect combination! ☕️🌧️ #RainyDayVibes",
];

const reactions = [
  "Amazing! 😍",
  "So cool! 🤩",
  "Congratulations! 🎉",
  "Beautiful place! 🌺",
  "Inspiring! 💪",
  "Movie nights are the best! 🍿🎥",
  "Incredible talent! 🎨✨",
  "Great recommendation! 📚",
  "Disconnect and recharge! 🌳🍃",
  "Love rainy days! ☔️☕️",
  "Wow! Impressive!",
  "Love it!",
  "Congrats!",
  "Stunning!",
  "Inspiring!",
  "Awesome!",
  "Fantastic!",
  "Great shot!",
  "Beautiful!",
  "Fantastic work!",
  "Wow! Amazing!",
  "So cool!",
  "Congrats! Well done!",
  "Impressive!",
  "Incredible!",
  "Love this!",
  "Fantastic job!",
  "You're killing it!",
  "Beautiful work!",
  "Bravo!",
];

const getRandomArrItem = (arr) => arr[Math.floor(Math.random() * arr.length)];

const getRandomUsername = () =>
  `${getRandomArrItem(usernames)}${Math.floor(
    Math.random() * (1000 - 18 + 1) + 18
  )}`;

const getRandomThought = () => `${getRandomArrItem(thoughts)}`;

const getRandomReaction = () => 
  `${getRandomArrItem(reactions)}`;

module.exports = { getRandomReaction, getRandomThought, getRandomUsername };
